(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")

(depends-on "auto-complete")
(depends-on "cask")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "dash")
(depends-on "elpy")
(depends-on "epl")
(depends-on "f")
(depends-on "find-file-in-project")
(depends-on "fuzzy")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "highlight-indentation")
(depends-on "idomenu")
(depends-on "iedit")
(depends-on "litable")
(depends-on "magit")
(depends-on "nose")
(depends-on "pallet")
(depends-on "popup")
(depends-on "s")
(depends-on "virtualenv")
(depends-on "yasnippet")